version: "3.8"

services:
  buccaneer:                      # The service name
    container_name: buccaneer
    build:
      context: /volume1/Documents/buccaneer   # Path to your Dockerfile
    command: ["python", "-u", "web_app.py"]
    volumes:
      - /volume1/Documents/buccaneer:/app    # Your code mounted inside container
      - /volume1/Music:/data              # Your music collection
    tty: true
    stdin_open: true
    ports:
      - "5100:5000"
    restart: unless-stopped

